// Users
// Create Account
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "firstName": "Marco",
    "lastName": "Polo",
    "department": "Admin",
    "email": "marcopoloo@gmail.com",
    "password": "1234"
}

###

// Login account
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "marcopoloo@gmail.com",
    "password": "1234"
}

###
// Get All Users / One User
GET http://localhost:5000/users

###
// Update User Profile
PUT http://localhost:5000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQyOTkzMDUsImV4cCI6MTYyNDM4NTcwNX0.lf2pmemVaPuWisv6kn_TvauO_Urulv-tVJQVUCDBhnw
Content-Type: application/json

{
    "firstName": "Marcos",
    "lastName": "Polos",
    "department": "Admin",
    "email": "marcouspolous@gmail.com",
    "password": "1234"
}

###
// Delete user account
DELETE http://localhost:5000/users/2


###

// Posts
// Create a post
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzNzc0NjY2LCJleHAiOjE2MjM4NjEwNjZ9.TQWtBy38i90yKYfJuNb73M09vGncrucJDQZ93vNGNJE

{
    "content": "Test pour update"
}

###
// Get all posts
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzNzc0NjY2LCJleHAiOjE2MjM4NjEwNjZ9.TQWtBy38i90yKYfJuNb73M09vGncrucJDQZ93vNGNJE

###
// Get one post
GET http://localhost:5000/posts/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQ0NDI1NjMsImV4cCI6MTYyNDUyODk2M30._hmVYp8jsFKg-62K6IEAujHNU52VdFbOs0gU_mfrIOw

###
// Update a post
PUT http://localhost:5000/posts/28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzNzc0NjY2LCJleHAiOjE2MjM4NjEwNjZ9.TQWtBy38i90yKYfJuNb73M09vGncrucJDQZ93vNGNJE

{
    "content": "Test update réussi ?"
}

###
// Delete a post
DELETE http://localhost:5000/posts/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzNzc0NjY2LCJleHAiOjE2MjM4NjEwNjZ9.TQWtBy38i90yKYfJuNb73M09vGncrucJDQZ93vNGNJE

###
// Comments
// Create a comment on a post
POST http://localhost:5000/posts/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQ0NDI1NjMsImV4cCI6MTYyNDUyODk2M30._hmVYp8jsFKg-62K6IEAujHNU52VdFbOs0gU_mfrIOw
Content-Type: application/json

{
    "content": "Test Commentaire 1",
    "PostId": "9"
}


###
// Get all comments from a post
GET http://localhost:5000/posts/1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDkwODk3MCwiZXhwIjoxNjIwOTk1MzcwfQ.8WM_LkGB1an6ATLR1AnF36BZOE5uQfVQJYFnpJbZUDU

###
// Delete a comment
DELETE http://localhost:5000/posts/1/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDkwODk3MCwiZXhwIjoxNjIwOTk1MzcwfQ.8WM_LkGB1an6ATLR1AnF36BZOE5uQfVQJYFnpJbZUDU
