// Users
// Create Account
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "firstName": "Ray",
    "lastName": "Allen",
    "department": "Admin",
    "email": "rayallen@gmail.com",
    "password": "1234"
}

###

// Login account
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "marcopolo@gmail.com",
    "password": "1234"
}

###
// Get All Users / One User
GET http://localhost:5000/users/2

###
// Update User Profile

###
// Delete user account
DELETE http://localhost:5000/users/2


###

// Posts
// Create a post
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTYyMDk5NjA4MiwiZXhwIjoxNjIxMDgyNDgyfQ.PVF_PvpBGtUK4MaHQDNA-Cy7lwHkghKbSyqh-sqhwKE

{
    "title": "Test post Ray Allen",
    "content": "Ceci est le premier test"
}

###
// Get all posts
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTYyMDk5NjA4MiwiZXhwIjoxNjIxMDgyNDgyfQ.PVF_PvpBGtUK4MaHQDNA-Cy7lwHkghKbSyqh-sqhwKE

###
// Get one post
GET http://localhost:5000/posts/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYyMDk5NTg2OSwiZXhwIjoxNjIxMDgyMjY5fQ.Tyz7EjY8skfwv0XRLghnae37r3B9e7Ir7yQl0R7T4s8

###
// Update a post
PUT http://localhost:5000/posts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDk5NjI3OCwiZXhwIjoxNjIxMDgyNjc4fQ.pPHeU1HQXoZcaKUrDVKtoXCggnDBd_3wi7IRVFzwuSQ

{
    "title": "Post bidon",
    "content": "Il n'a plus d'user"
}

###
// Delete a post
DELETE http://localhost:5000/posts/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDk5NjU0MywiZXhwIjoxNjIxMDgyOTQzfQ.9-IgBL7f-sTQFVAASo5yZ9SY4zFgsUhf_dzjE3IU81w

###
// Comments
// Create a comment on a post
POST http://localhost:5000/posts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTYyMDk5NjA4MiwiZXhwIjoxNjIxMDgyNDgyfQ.PVF_PvpBGtUK4MaHQDNA-Cy7lwHkghKbSyqh-sqhwKE

{
    "content": "Test avec authentification"
}


###
// Get all comments from a post
GET http://localhost:5000/posts/1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDkwODk3MCwiZXhwIjoxNjIwOTk1MzcwfQ.8WM_LkGB1an6ATLR1AnF36BZOE5uQfVQJYFnpJbZUDU

###
// Delete a comment
DELETE http://localhost:5000/posts/1/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDkwODk3MCwiZXhwIjoxNjIwOTk1MzcwfQ.8WM_LkGB1an6ATLR1AnF36BZOE5uQfVQJYFnpJbZUDU
