// Users
// Create Account
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "firstName": "Marco",
    "lastName": "Polo",
    "department": "Admin",
    "email": "marcopolo@gmail.com",
    "password": "1234"
}

###

// Login account
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "marcopolo@gmail.com",
    "password": "1234"
}

###
// Get All Users / One User
GET http://localhost:5000/users/2

###
// Update User Profile

###
// Delete user account
DELETE http://localhost:5000/users/2


###

// Posts
// Create a post
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzMTQ5MDk0LCJleHAiOjE2MjMyMzU0OTR9.LoqoObtk194QBaRsnSOZhqfFp-Y4fXYWOAL41EHvWYU

{
    "content": "Test Token"
}

###
// Get all posts
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjE5Nzc3NjUsImV4cCI6MTYyMjA2NDE2NX0.VsqeRIv5Y725kQOkLCn4DxgOOC7KNvybilWKrtCSy9M

###
// Get one post
GET http://localhost:5000/posts/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTYyMTAwMjg1NiwiZXhwIjoxNjIxMDg5MjU2fQ.ojefc0l58LoCfrDz8qkHOJM_e6qsF89djP9_5LPT3jA

###
// Update a post
PUT http://localhost:5000/posts/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTYyMTAwMjg1NiwiZXhwIjoxNjIxMDg5MjU2fQ.ojefc0l58LoCfrDz8qkHOJM_e6qsF89djP9_5LPT3jA

{
    "title": "Post bidon",
    "content": "Il n'a plus d'user"
}

###
// Delete a post
DELETE http://localhost:5000/posts/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMTAwNTc4NCwiZXhwIjoxNjIxMDkyMTg0fQ.nCVbv6kJ9uIJ443yuSJ4f73HgzhNAb14QUsHhg0FgNo

###
// Comments
// Create a comment on a post
POST http://localhost:5000/posts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTYyMDk5NjA4MiwiZXhwIjoxNjIxMDgyNDgyfQ.PVF_PvpBGtUK4MaHQDNA-Cy7lwHkghKbSyqh-sqhwKE

{
    "content": "Test avec authentification"
}


###
// Get all comments from a post
GET http://localhost:5000/posts/1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDkwODk3MCwiZXhwIjoxNjIwOTk1MzcwfQ.8WM_LkGB1an6ATLR1AnF36BZOE5uQfVQJYFnpJbZUDU

###
// Delete a comment
DELETE http://localhost:5000/posts/1/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYyMDkwODk3MCwiZXhwIjoxNjIwOTk1MzcwfQ.8WM_LkGB1an6ATLR1AnF36BZOE5uQfVQJYFnpJbZUDU
